AllCops:
  TargetRubyVersion: 2.5.0
  Exclude:
    - '.git-hooks/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'

Style/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
